apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spirapi-data-pvc
  namespace: spirapi
  labels:
    app: spirapi
    component: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spirapi-logs-pvc
  namespace: spirapi
  labels:
    app: spirapi
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spirapi-redis-pvc
  namespace: spirapi
  labels:
    app: spirapi
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spirapi-postgres-pvc
  namespace: spirapi
  labels:
    app: spirapi
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spirapi-prometheus-pvc
  namespace: spirapi
  labels:
    app: spirapi
    component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spirapi-grafana-pvc
  namespace: spirapi
  labels:
    app: spirapi
    component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
